=== datakaveri/differential-privacy/config/anonymizationSchema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
	  "dataFile": {
		"type": "string"
	  },
	  "genType": {
		"type": "string"
	  },
	  "spatio-temporal": {
		"type": "object",
		"properties": {
		  "duplicateDetection": {
			"type": "array",
			"maxItems": 2,
			"minItems": 2,
			"uniqueItems": true,
			"items": [
			  {
				"type": "string"
			  }
			]
		  },
		  "suppressCols": {
			"type": "array",
			"items": [
			  {
				"type": "string"
			  }
			]
		  },
		  "outputOptions": {
			"maximum": 3,
			"minimum": 0,
			"type": "integer"
		  },
		  "pseudoCol": {
			"type": "string"
		  },
		  "locationCol": {
			"type": "string"
		  },
		  "datetimeCol": {
			"type": "string"
		  },
		  "trueValue": {
			"type": "string"
		  },
		  "groupByCol": {
			"type": "string"
		  },
		  "localityFactor": {
			"maximum": 1,
			"minimum": 0,
			"type": "integer"
		  },
		  "winsorizeLowerBound": {
			"maximum": 0.1,
			"minimum": 0.01,
			"type": "number"
		  },
		  "winsorizeUpperBound": {
			"maximum": 1.0,
			"minimum": 0.9,
			"type": "number"
		  },
		  "globalMaxValue": {
			"maximum": 200,
			"minimum": 0,
			"type": "integer"
		  },
		  "globalMinValue": {
			"maximum": 200,
			"minimum": 0,
			"type": "integer"
		  },
		  "privacyLossBudgetEpsQuery": {
			"type": "array",
			"items": {
			  "type": "number"  
			},
			"maximum": 100,
			"minimum": 0
		  },
		  "h3Resolution": {
			"minimum": 6,
			"maximum": 8,
			"type": "integer"
		  },
		  "startTime": {
			"minimum": 0,
			"maximum": 23,
			"type": "integer"
		  },
		  "endTime": {
			"minimum": 0,
			"maximum": 23,
			"type": "integer"
		  },
		  "minEventOccurences": {
			"type": "integer"
		  },
		  "trueValueThreshold": {
			"type": "integer"
		  },
		  "snrUpperLimit": {
			"type": "integer"
		  },
		  "snrLowerLimit": {
			"type": "integer"
		  }
		},
		"required": [    
		"duplicateDetection",
		"suppressCols",
		"outputOptions",
		"pseudoCol",
		"locationCol",
		"datetimeCol",
		"groupByCol",
		"localityFactor",
		"winsorizeLowerBound",
		"winsorizeUpperBound",
		"globalMaxValue",
		"globalMinValue",
		"privacyLossBudgetEpsQuery",
		"h3Resolution",
		"startTime",
		"endTime",
		"minEventOccurences",
		"trueValueThreshold",
		"snrLowerLimit",
		"snrUpperLimit"
		]
	  },
	  "categorical": {
		"type": "object",
		"properties": {
		  "duplicateDetection": {
			"type": "array",
			"items": [
			  {
				"type": "string"
			  }
			]
		  },
		  "queryPer": {
			"type": "string"
		  },
		  "splitCols": {
			"type": "array",
			"items": [
			  {
				"type": "string"
			  }
			]
		  },
		  "suppressCols": {
			"type": "array",
			"items": [
			  {
				"type": "string"
			  }
			]
		  },
		  "groupByCols": {
			"type": "array",
			"items": [
			  {
				"type": "string"
			  }
			]
		  },
		  "groupByPairs": {
			"type": "array",
			"items": [
			  {
				"type": "array",
				"items": [
				  {
					"type": "string"
				  },
				  {
					"type": "string"
				  }
				]
			  },
			  {
				"type": "array",
				"items": [
				  {
					"type": "string"
				  },
				  {
					"type": "string"
				  }
				]
			  },
			  {
				"type": "array",
				"items": [
				  {
					"type": "string"
				  },
				  {
					"type": "string"
				  }
				]
			  },
			  {
				"type": "array",
				"items": [
				  {
					"type": "string"
				  },
				  {
					"type": "string"
				  }
				]
			  }
			]
		  },
		  "ID": {
			"type": "string"
		  },
		  "cycleToDrop": {
			"type": "array",
			"items": [
			  {
				"type": "string"
			  }
			]
		  },
		  "cycleToKeep": {
			"type": "array",
			"items": [
			  {
				"type": "string"
			  }
			]
		  },
		  "PrivacyLossBudget": {
			"type": "array",
			"items": [
			  {
				"type": "integer"
			  },
			  {
				"type": "integer"
			  }
			]
		  },
		  "snrUpperLimit": {
			"type": "integer"
		  },
		  "snrLowerLimit": {
			"type": "integer"
		  },
		  "outputOptions": {
			"type": "integer"
		  }
		},
		"required": [
		  "duplicateDetection",
		  "queryPer",
		  "splitCols",
		  "suppressCols",
		  "groupByCols",
		  "groupByPairs",
		  "ID",
		  "cycleToDrop",
		  "cycleToKeep",
		  "PrivacyLossBudget",
		  "snrUpperLimit",
		  "snrLowerLimit",
		  "outputOptions"
		]
	  },
	  "genAgg": {
		"type": "object",
		"properties": {
		  "duplicateDetection": {
			"type": "array",
			"items": {}
		  },
		  "suppressCols": {
			"type": "array",
			"items": [
			  {
				"type": "string"
			  },
			  {
				"type": "string"
			  }
			]
		  },
		  "datetimeCol": {
			"type": "string"
		  }
		},
		"required": [
		  "duplicateDetection",
		  "suppressCols",
		  "datetimeCol"
		]
	  }
	},
	"required": [
	  "dataFile",
	  "genType",
	  "spatio-temporal",
	  "categorical",
	  "genAgg"
	]
  }

=== datakaveri/differential-privacy/config/anonymizationConfig.json
{
	"dataFile": "",
	"genType": "",
	"spatio-temporal": {
		"duplicateDetection": [
			"trip_id",
			"observationDateTime"
		],
		"suppressCols": [
			"trip_direction",
			"last_stop_arrival_time",
			"route_id",
			"actual_trip_start_time",
			"trip_delay",
			"vehicle_label",
			"id",
			"location.type",
			"trip_id"
		],
		"outputOptions": 0,
		"pseudoCol": "license_plate",
		"locationCol": "location.coordinates",
		"datetimeCol": "observationDateTime",
		"trueValue": "speed",
		"groupByCol": "speed",
		"localityFactor": 0,
		"winsorizeLowerBound": 0.01,
		"winsorizeUpperBound": 0.99,
		"globalMaxValue": 65,
		"globalMinValue": 0, 
		"privacyLossBudgetEpsQuery": [
			10,
			10
		],
		"h3Resolution": 7,
		"startTime": 9,
		"endTime": 20,
		"minEventOccurences": 30,
		"trueValueThreshold": 35,
		"snrUpperLimit" : 3,
		"snrLowerLimit" : 0
	},
	"categorical": {
		"duplicateDetection": [
			"Sample No."
		],
		"queryPer":"subdistrict",
		"splitCols":[
			"pH",
			"EC",
			"OC",
			"N",
			"P",
			"K",
			"S",
			"Zn",
			"Fe",
			"Cu", 
			"Mn", 
			"B"],
		"suppressCols": [
			"Farmer Name",
			"Land Area",
			"Khasra No./ Dag No.",
			"Survey No.",
			"Longitude",
			"Latitude"],
		"groupByCols":[
			"N",
			"P",
			"K"
		],
		"groupByPairs":[["N","P"], ["Zn","Fe"],["N","pH"],["OC","EC"]],
		"ID":"Sample No.",
		"cycleToDrop":["2019-20-to-2020-2021"],
		"cycleToKeep":["2017-18-to-2018-19"],
		"PrivacyLossBudget":[5, 5],
		"snrUpperLimit" : 3,
		"snrLowerLimit" : 0,
		"outputOptions": 0	
		},
	"genAgg":{
		"duplicateDetection": [],
		"suppressCols": ["subCategory","comments"],
		"datetimeCol": "observationDateTime"	
		}
}
